name: conch_extract_features
repo:
  name: CONCH
  url: "https://github.com/mahmoodlab/CONCH"
  commit: 171f2be
  env:
    HF_TOKEN: "${env:HF_TOKEN}"  # required for downloading models
papers: [lu2024conch]
category: pathology
description: Perform feature extraction on an input image using CONCH.
arguments:
  input_image:
    description: Path to the input image
    type: str
returns:
  features:
    description: The feature vector extracted from the input image, as a list of floats
    type: list
example:
  arguments:
    input_image: /mount/input/TUM-TCGA-ACRLPPQE.tif
  mount:
    TUM-TCGA-ACRLPPQE.tif: TUM-TCGA-ACRLPPQE.tif
test_invocations:
  tif:
    arguments:
      input_image: /mount/input/MUC/MUC-TCGA-ACCPKIPN.tif
    mount:
      MUC-TCGA-ACCPKIPN.tif: MUC/MUC-TCGA-ACCPKIPN.tif
  png:
    arguments:
      input_image: /mount/input/TCGA-BRCA_patch_TCGA-BH-A0DE-01Z-00-DX1.64A0340A-8146-48E8-AAF7-4035988B9152.png
    mount:
      TCGA-BRCA_patch_TCGA-BH-A0DE-01Z-00-DX1.64A0340A-8146-48E8-AAF7-4035988B9152.png: TCGA-BRCA_patch_TCGA-BH-A0DE-01Z-00-DX1.64A0340A-8146-48E8-AAF7-4035988B9152.png
  jpg:
    arguments:
      input_image: /mount/input/TCGA-BRCA_patch_TCGA-BH-A0DE-01Z-00-DX1.64A0340A-8146-48E8-AAF7-4035988B9152.jpg
    mount:
      TCGA-BRCA_patch_TCGA-BH-A0DE-01Z-00-DX1.64A0340A-8146-48E8-AAF7-4035988B9152.jpg: TCGA-BRCA_patch_TCGA-BH-A0DE-01Z-00-DX1.64A0340A-8146-48E8-AAF7-4035988B9152.jpg

